apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: observability-demo
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: observability-demo
  endpoints:
  - port: http
    path: /metrics